package sistemacaja;

import javax.swing.JOptionPane;

/**
 *
 * @author Planificacion1
 */
public class frmMenu extends javax.swing.JFrame {
    
    
    conexion con = new conexion();
    private PrintReportDiario jasper;
    /**
     * Creates new form frmRecibos
     */
    public frmMenu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnReciboSolicitudes = new javax.swing.JButton();
        btnRecivosDNI = new javax.swing.JButton();
        btnReporteDiario = new javax.swing.JButton();
        btnReporteMensual = new javax.swing.JButton();
        btnAnularRecibo = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(520, 400));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnReciboSolicitudes.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        btnReciboSolicitudes.setText("RECIBOS POR SOLICITUDES");
        btnReciboSolicitudes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReciboSolicitudesActionPerformed(evt);
            }
        });
        getContentPane().add(btnReciboSolicitudes, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 60, -1, -1));

        btnRecivosDNI.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        btnRecivosDNI.setText("RECIBOS POR DNI");
        btnRecivosDNI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRecivosDNIActionPerformed(evt);
            }
        });
        getContentPane().add(btnRecivosDNI, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 120, -1, -1));

        btnReporteDiario.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        btnReporteDiario.setText("REPORTE DIARIO");
        btnReporteDiario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReporteDiarioActionPerformed(evt);
            }
        });
        getContentPane().add(btnReporteDiario, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 170, -1, -1));

        btnReporteMensual.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        btnReporteMensual.setText("REPORTE MENSUAL");
        getContentPane().add(btnReporteMensual, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 230, -1, -1));

        btnAnularRecibo.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        btnAnularRecibo.setText("ANULAR RECIBOS");
        getContentPane().add(btnAnularRecibo, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 290, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnReciboSolicitudesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReciboSolicitudesActionPerformed
      frmRecSolicitud Recibo=new frmRecSolicitud();
        Recibo.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnReciboSolicitudesActionPerformed

    private void btnRecivosDNIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRecivosDNIActionPerformed
        frmRecDNI Recibo=new frmRecDNI();
        Recibo.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnRecivosDNIActionPerformed

    private void btnReporteDiarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReporteDiarioActionPerformed
        // TODO add your handling code here:
        String fecha = JOptionPane.showInputDialog(rootPane, "Ingrese Fecha (Año-Mes-dia)");
        jasper.ejecutarReporte(fecha);
    }//GEN-LAST:event_btnReporteDiarioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAnularRecibo;
    private javax.swing.JButton btnReciboSolicitudes;
    private javax.swing.JButton btnRecivosDNI;
    private javax.swing.JButton btnReporteDiario;
    private javax.swing.JButton btnReporteMensual;
    // End of variables declaration//GEN-END:variables
}
